export default {
  HomeImg: require('../assets/images/Home.png'),
  Logo: require('../assets/images/Logo.png'),
  Avatar: require('../assets/images/Avatar.png'),
  wellness: require('../assets/images/wellness.png'),
  user: require('../assets/images/dashboard/user.png'),
  clientavatar: require('../assets/images/clientavatar.jpeg'),
  profile: require('../assets/images/profile.png'),
  water: require('../assets/images/water.png'),
  task: require('../assets/images/task.png'),
  drop: require('../assets/images/drop.png'),
  profile1: require('../assets/images/profile1.jpg'),
  profile2: require('../assets/images/profile2.jpg'),
  profile3: require('../assets/images/profile3.jpg'),
  profile4: require('../assets/images/profile4.jpg'),
  profile5: require('../assets/images/profile5.jpg'),
  profile6: require('../assets/images/profile6.jpg'),
  profile7: require('../assets/images/profile7.jpg'),
  profile8: require('../assets/images/profile8.jpg'),
  profile9: require('../assets/images/profile9.jpg'),
  sleepmood: require('../assets/images/dashboard/sleepmood.png'),
  excercise: require('../assets/images/dashboard/excercise.png'),
  //   brain: require('../assets/images/brain.png'),
};
